// Generated by @colibri/contract-bindings. Replaceable: keep custom code outside this file.
/**
 * Typed Colibri client for Protocol28.
 * @module
 */
import {
  Contract,
  type ContractId,
  createContractErrorMatcherPlugin,
} from "@colibri/core";
import { Spec } from "@colibri/core";
import { ContractMethods, Protocol28Errors, Protocol28Spec } from "./constants.ts";
import type {
  Protocol28Call,
  Protocol28ConstructorArgs,
  Protocol28Events,
  Protocol28Invocation,
  Protocol28InvocationResult,
  Protocol28Method,
  Protocol28MethodMap,
  Protocol28Outputs,
} from "./types.ts";

export * from "./constants.ts";
export * from "./types.ts";
export {
  ColibriError,
  LocalSigner,
  NetworkConfig,
  SorobanType,
} from "./colibri.ts";
export type {
  AuthEntrySigner,
  ContractConfig,
  ContractConstructorArgs,
  ContractId,
  Ed25519PublicKey,
  EnvelopeSigner,
  KeypairSigner,
  Signer,
  TransactionConfig,
} from "./colibri.ts";

/** Simulate or invoke callable functions declared in the embedded contract spec. */
export class Protocol28 extends Contract {
  /** Simulate or invoke echo. */
  readonly echo: Protocol28Method<"echo"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.Echo, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.Echo,
      }),
  };

  /** Simulate or invoke updates. */
  readonly updates: Protocol28Method<"updates"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.Updates, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.Updates,
      }),
  };

  /** Simulate or invoke transfers. */
  readonly transfers: Protocol28Method<"transfers"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.Transfers, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.Transfers,
      }),
  };

  /** Install a fresh spec and the prepared error map alongside existing plugins. */
  constructor({ errors = Protocol28Errors, ...args }: Protocol28ConstructorArgs) {
    const contractId = args.contractConfig.contractId as ContractId | undefined;
    const matcher = errors === false || Object.keys(errors).length === 0
      ? undefined
      : createContractErrorMatcherPlugin(
        contractId ? [{ strategy: "contract-id", contractId, errors }] : [{
          strategy: "issued-from",
          issuedFrom: "root-invocation",
          errors,
        }],
      );
    const plugins = args.contractConfig.plugins;

    super({
      ...args,
      contractConfig: {
        ...args.contractConfig,
        spec: new Spec(Protocol28Spec.entries.map((entry) => entry.toXdr("base64"))),
        plugins: {
          invokePipe: [
            ...(matcher ? [matcher] : []),
            ...(plugins?.invokePipe ?? []),
          ],
          readPipe: [
            ...(matcher ? [matcher] : []),
            ...(plugins?.readPipe ?? []),
          ],
        },
      },
    });
  }

  /** Access event definitions bound to the current contract ID. */
  override get events(): Protocol28Events {
    return super.events as Protocol28Events;
  }

  /** Simulate a function and decode its result without submitting a transaction. */
  override async read<Method extends keyof Protocol28MethodMap>(
    args: Protocol28Call<Method>,
  ): Promise<Protocol28Outputs[Method]> {
    return await super.read(args) as Protocol28Outputs[Method];
  }

  /** Submit through Colibri and retain both the decoded value and raw result. */
  override async invoke<Method extends keyof Protocol28MethodMap>(
    args: Protocol28Call<Method> & Protocol28Invocation,
  ): Promise<Protocol28InvocationResult<Protocol28Outputs[Method]>> {
    const result = await super.invoke(args);
    return this.decodeInvocationResult<Protocol28Outputs[Method]>(
      args.method,
      result,
    );
  }
}
