// Generated by @colibri/contract-bindings. Replaceable: keep custom code outside this file.
/**
 * Protocol28 contract types, function arguments, results, and events.
 * @module
 */
import type {
  Contract,
  ContractConstructorArgs,
  ContractErrorMap,
  ContractEventDefinition,
  ContractEventRegistry,
} from "@colibri/core";
import { SorobanType } from "@colibri/core";
import { Protocol28Spec } from "./constants.ts";

// -----------------------------------------------------------------------------
// Methods
// -----------------------------------------------------------------------------

/** Arguments for echo. */
export type EchoInput = {
  state: StateArgs;
};

/** Decoded return value of echo. */
export type EchoOutput = State;

/** Arguments for updates. */
export type UpdatesInput = {
  a: SorobanType.Input.Option<SorobanType.Input.U32, SorobanType.U32>;
  b: SorobanType.Input.U32;
};

/** Decoded return value of updates. */
export type UpdatesOutput = null;

/** Arguments for transfers. */
export type TransfersInput = {
  from: SorobanType.Input.Address;
  to: SorobanType.Input.Address;
  id: SorobanType.Input.Option<SorobanType.Input.U64, SorobanType.U64>;
};

/** Decoded return value of transfers. */
export type TransfersOutput = null;

/** Callable ABI methods available through read and invoke; excludes __constructor. */
export type Protocol28MethodMap = {
  echo: {
    input: EchoInput;
    output: EchoOutput;
  };
  updates: {
    input: UpdatesInput;
    output: UpdatesOutput;
  };
  transfers: {
    input: TransfersInput;
    output: TransfersOutput;
  };
};

/** Method names mapped to their accepted arguments. */
export type Protocol28Inputs = {
  [Method in keyof Protocol28MethodMap]: Protocol28MethodMap[Method]["input"];
};

/** Method names mapped to their decoded return values. */
export type Protocol28Outputs = {
  [Method in keyof Protocol28MethodMap]: Protocol28MethodMap[Method]["output"];
};

/** A method and its matching arguments; argument-free calls may omit methodArgs. */
export type Protocol28Call<Method extends keyof Protocol28MethodMap> = {
  [Name in Method]:
    & { method: Name }
    & (
      Protocol28Inputs[Name] extends Record<string, never>
        ? { methodArgs?: Protocol28Inputs[Name] }
        : { methodArgs: Protocol28Inputs[Name] }
    );
}[Method];

/** Transaction settings and authorization passed to Colibri. */
export type Protocol28Invocation = Pick<
  Parameters<Contract["invoke"]>[0],
  "config" | "auth"
>;

/** Core transaction metadata and the decoded contract result. */
export type Protocol28InvocationResult<Value> =
  & Awaited<ReturnType<Contract["invoke"]>>
  & { value: Value | undefined };

/** Bound read/invoke helpers for one ABI method, with its exact input and output. */
export type Protocol28Method<Method extends keyof Protocol28MethodMap> = {
  /** Simulate without submitting; argument-free methods can omit the input. */
  readonly read: (
    ...args: Protocol28Inputs[Method] extends Record<string, never>
      ? [methodArgs?: Protocol28Inputs[Method]]
      : [methodArgs: Protocol28Inputs[Method]]
  ) => Promise<Protocol28Outputs[Method]>;
  /** Submit with the generic invocation object, omitting only the fixed method. */
  readonly invoke: (
    args: Omit<Protocol28Call<Method>, "method"> & Protocol28Invocation,
  ) => Promise<Protocol28InvocationResult<Protocol28Outputs[Method]>>;
};

// -----------------------------------------------------------------------------
// Contract types
// -----------------------------------------------------------------------------

/** The State type declared by the contract. */
export type State = SorobanType.Custom<{
  kind: "struct";
  fields: {
    a: SorobanType.Option<SorobanType.U32>;
    b: SorobanType.U32;
    c: SorobanType.Option<SorobanType.U32>;
  };
}>;

/** Raw or validated values accepted by the State factory. */
export type StateArgs = SorobanType.Input.Custom<State>;

/** Validate, encode and decode State using its contract declaration. */
export const State: SorobanType.Factory<State> = SorobanType
  .Custom.fromSpec<State>(
    () => Protocol28Spec,
    "State",
  );

// -----------------------------------------------------------------------------
// Events
// -----------------------------------------------------------------------------

/** Fields emitted by Transfer. */
export type Transfer = {
  from: SorobanType.Address;
  to: SorobanType.Address;
  amount: SorobanType.I128;
};

/** Indexed fields accepted by the Transfer event filters. */
export type TransferTopics = {
  from: SorobanType.Input.Address;
  to: SorobanType.Input.Address;
};

/** Fields emitted by DenseUpdate. */
export type DenseUpdate = {
  a: SorobanType.Option<SorobanType.U32>;
  b: SorobanType.U32;
};

/** Indexed fields accepted by the DenseUpdate event filters. */
export type DenseUpdateTopics = Record<string, never>;

/** Fields emitted by SparseUpdate. */
export type SparseUpdate = {
  a: SorobanType.Option<SorobanType.U32>;
  b: SorobanType.U32;
};

/** Indexed fields accepted by the SparseUpdate event filters. */
export type SparseUpdateTopics = Record<string, never>;

/** Fields emitted by MuxedTransfer. */
export type MuxedTransfer = {
  from: SorobanType.Address;
  to: SorobanType.Address;
  to_muxed_id: SorobanType.Option<SorobanType.U64>;
  amount: SorobanType.I128;
};

/** Indexed fields accepted by the MuxedTransfer event filters. */
export type MuxedTransferTopics = {
  from: SorobanType.Input.Address;
  to: SorobanType.Input.Address;
};

/** Event definitions bound to this client, with typed decoding and filters. */
export type Protocol28Events = ContractEventRegistry & {
  readonly Transfer: ContractEventDefinition<
    Transfer,
    TransferTopics
  >;
  readonly DenseUpdate: ContractEventDefinition<
    DenseUpdate,
    DenseUpdateTopics
  >;
  readonly SparseUpdate: ContractEventDefinition<
    SparseUpdate,
    SparseUpdateTopics
  >;
  readonly MuxedTransfer: ContractEventDefinition<
    MuxedTransfer,
    MuxedTransferTopics
  >;
};

// -----------------------------------------------------------------------------
// Client configuration
// -----------------------------------------------------------------------------

/** Configure the contract and prepare error messages before construction. */
export type Protocol28ConstructorArgs = ContractConstructorArgs & {
  errors?: ContractErrorMap | false;
};
