const STELLAR_CLI_VERSION = "26.1.0";
const SOROBAN_SDK_VERSION = "22.0.8";

const fixtures = [
  {
    package: "web-auth-contract",
    wasm: "web_auth_contract.wasm",
    spec: "web-auth.ts",
    exportName: "WEB_AUTH_SPEC",
  },
  {
    package: "passkey-account-contract",
    wasm: "passkey_account_contract.wasm",
    spec: "passkey-account.ts",
    exportName: "PASSKEY_ACCOUNT_SPEC",
  },
  {
    package: "signatureless-account-contract",
    wasm: "signatureless_account_contract.wasm",
    spec: "signatureless-account.ts",
    exportName: "SIGNATURELESS_ACCOUNT_SPEC",
  },
] as const;

const check = Deno.args.includes("--check");
const root = new URL("../", import.meta.url);
const artifactDirectory = new URL(
  "_internal/tests/compiled-contracts/",
  root,
);
const specDirectory = new URL("_internal/tests/specs/", root);
const manifestUrl = new URL(
  "webauth-fixtures.sha256.json",
  artifactDirectory,
);

async function command(
  executable: string,
  args: string[],
): Promise<string> {
  const output = await new Deno.Command(executable, {
    args,
    cwd: root,
    stdout: "piped",
    stderr: "inherit",
  }).output();
  if (!output.success) {
    throw new Error(`${executable} ${args.join(" ")} failed`);
  }
  return new TextDecoder().decode(output.stdout).trim();
}

async function assertPinnedVersions(): Promise<void> {
  const stellarVersion = await command("stellar", ["--version"]);
  if (!stellarVersion.includes(`stellar ${STELLAR_CLI_VERSION}`)) {
    throw new Error(
      `Expected Stellar CLI ${STELLAR_CLI_VERSION}, got ${stellarVersion}`,
    );
  }
  const cargoManifest = await Deno.readTextFile(new URL("Cargo.toml", root));
  if (!cargoManifest.includes(`soroban-sdk = "${SOROBAN_SDK_VERSION}"`)) {
    throw new Error(
      `Expected workspace soroban-sdk ${SOROBAN_SDK_VERSION}`,
    );
  }
}

async function sha256(value: Uint8Array): Promise<string> {
  const digest = await crypto.subtle.digest(
    "SHA-256",
    Uint8Array.from(value),
  );
  return Array.from(new Uint8Array(digest))
    .map((byte) => byte.toString(16).padStart(2, "0"))
    .join("");
}

function specSource(
  exportName: string,
  entries: string[],
): string {
  const lines = entries.map((entry) => `  ${JSON.stringify(entry)},`);
  return [
    "// deno-coverage-ignore-file",
    "// Generated by _tools/build-webauth-fixtures.ts. Do not edit.",
    'import { Spec } from "stellar-sdk/contract";',
    "",
    `export const ${exportName} = new Spec([`,
    ...lines,
    "]);",
    "",
  ].join("\n");
}

async function sameFile(url: URL, expected: Uint8Array): Promise<boolean> {
  try {
    const actual = await Deno.readFile(url);
    return actual.length === expected.length &&
      actual.every((byte, index) => byte === expected[index]);
  } catch (cause) {
    if (cause instanceof Deno.errors.NotFound) return false;
    throw cause;
  }
}

await assertPinnedVersions();
const buildDirectory = await Deno.makeTempDir({
  prefix: "colibri-webauth-fixtures-",
});
const hashes: Record<string, string> = {};
const stale: string[] = [];

try {
  for (const fixture of fixtures) {
    await command("stellar", [
      "contract",
      "build",
      "--locked",
      "--package",
      fixture.package,
      "--out-dir",
      buildDirectory,
    ]);
    const builtUrl = new URL(
      fixture.wasm,
      `file://${buildDirectory.replace(/\/?$/, "/")}`,
    );
    const wasm = await Deno.readFile(builtUrl);
    const entries = JSON.parse(
      await command("stellar", [
        "contract",
        "inspect",
        "--wasm",
        builtUrl.pathname,
        "--output",
        "xdr-base64-array",
      ]),
    ) as string[];
    const spec = new TextEncoder().encode(
      specSource(fixture.exportName, entries),
    );
    const artifactUrl = new URL(fixture.wasm, artifactDirectory);
    const specUrl = new URL(fixture.spec, specDirectory);
    hashes[fixture.wasm] = await sha256(wasm);

    if (check) {
      if (!(await sameFile(artifactUrl, wasm))) stale.push(fixture.wasm);
      if (!(await sameFile(specUrl, spec))) stale.push(fixture.spec);
    } else {
      await Deno.mkdir(artifactDirectory, { recursive: true });
      await Deno.mkdir(specDirectory, { recursive: true });
      await Deno.writeFile(artifactUrl, wasm);
      await Deno.writeFile(specUrl, spec);
    }
  }

  const manifest = new TextEncoder().encode(
    `${
      JSON.stringify(
        {
          stellarCli: STELLAR_CLI_VERSION,
          sorobanSdk: SOROBAN_SDK_VERSION,
          artifacts: hashes,
        },
        null,
        2,
      )
    }\n`,
  );
  if (check) {
    if (!(await sameFile(manifestUrl, manifest))) {
      stale.push("webauth-fixtures.sha256.json");
    }
    if (stale.length > 0) {
      throw new Error(
        `Stale WebAuth fixtures: ${stale.join(", ")}`,
      );
    }
  } else {
    await Deno.writeFile(manifestUrl, manifest);
  }
} finally {
  await Deno.remove(buildDirectory, { recursive: true });
}
