const STELLAR_CLI_VERSION = "26.1.0";
const SOROBAN_SDK_VERSION = "26.1.1";
const STELLAR_TOKENS_VERSION = "0.7.2";

const check = Deno.args.includes("--check");
const root = new URL("../", import.meta.url);
const manifest = "_internal/contracts/sep41-token/Cargo.toml";
const wasmName = "sep41_token_contract.wasm";
const specName = "sep41-token.ts";
const artifactDirectory = new URL("_internal/tests/compiled-contracts/", root);
const specDirectory = new URL("_internal/tests/specs/", root);
const hashManifestUrl = new URL("sep41-fixture.sha256.json", artifactDirectory);

const command = async (executable: string, args: string[]): Promise<string> => {
  const output = await new Deno.Command(executable, {
    args,
    cwd: root,
    stdout: "piped",
    stderr: "inherit",
  }).output();
  if (!output.success) {
    throw new Error(`${executable} ${args.join(" ")} failed`);
  }
  return new TextDecoder().decode(output.stdout).trim();
};

const sameFile = async (url: URL, expected: Uint8Array): Promise<boolean> => {
  try {
    const actual = await Deno.readFile(url);
    return actual.length === expected.length &&
      actual.every((byte, index) => byte === expected[index]);
  } catch (cause) {
    if (cause instanceof Deno.errors.NotFound) return false;
    throw cause;
  }
};

const sha256 = async (value: Uint8Array): Promise<string> => {
  const digest = await crypto.subtle.digest("SHA-256", Uint8Array.from(value));
  return Array.from(new Uint8Array(digest))
    .map((byte) => byte.toString(16).padStart(2, "0"))
    .join("");
};

const specSource = (entries: string[]): Uint8Array =>
  new TextEncoder().encode([
    "// deno-coverage-ignore-file",
    "// Generated by _tools/build-sep41-fixture.ts. Do not edit.",
    'import { Spec } from "stellar-sdk/contract";',
    "",
    "export const SEP41_TOKEN_SPEC = new Spec([",
    ...entries.map((entry) => `  ${JSON.stringify(entry)},`),
    "]);",
    "",
  ].join("\n"));

const stellarVersion = await command("stellar", ["--version"]);
if (!stellarVersion.includes(`stellar ${STELLAR_CLI_VERSION}`)) {
  throw new Error(
    `Expected Stellar CLI ${STELLAR_CLI_VERSION}, got ${stellarVersion}`,
  );
}

const cargoManifest = await Deno.readTextFile(new URL(manifest, root));
for (
  const expected of [
    `soroban-sdk = "=${SOROBAN_SDK_VERSION}"`,
    `stellar-tokens = "${STELLAR_TOKENS_VERSION}"`,
  ]
) {
  if (!cargoManifest.includes(expected)) {
    throw new Error(`Missing pinned fixture dependency: ${expected}`);
  }
}

const buildDirectory = await Deno.makeTempDir({ prefix: "colibri-sep41-" });
const stale: string[] = [];
try {
  await command("stellar", [
    "contract",
    "build",
    "--locked",
    "--package",
    "sep41-token-contract",
    "--out-dir",
    buildDirectory,
  ]);
  const builtUrl = new URL(
    wasmName,
    `file://${buildDirectory.replace(/\/?$/, "/")}`,
  );
  const wasm = await Deno.readFile(builtUrl);
  const entries = JSON.parse(
    await command("stellar", [
      "contract",
      "inspect",
      "--wasm",
      builtUrl.pathname,
      "--output",
      "xdr-base64-array",
    ]),
  ) as string[];
  const spec = specSource(entries);
  const hash = await sha256(wasm);
  const hashManifest = new TextEncoder().encode(`${
    JSON.stringify(
      {
        stellarCli: STELLAR_CLI_VERSION,
        sorobanSdk: SOROBAN_SDK_VERSION,
        stellarTokens: STELLAR_TOKENS_VERSION,
        artifact: { [wasmName]: hash },
      },
      null,
      2,
    )
  }\n`);
  const artifactUrl = new URL(wasmName, artifactDirectory);
  const specUrl = new URL(specName, specDirectory);

  if (check) {
    if (!(await sameFile(artifactUrl, wasm))) stale.push(wasmName);
    if (!(await sameFile(specUrl, spec))) stale.push(specName);
    if (!(await sameFile(hashManifestUrl, hashManifest))) {
      stale.push("sep41-fixture.sha256.json");
    }
    if (stale.length > 0) {
      throw new Error(`Stale SEP-41 fixtures: ${stale.join(", ")}`);
    }
  } else {
    await Deno.mkdir(artifactDirectory, { recursive: true });
    await Deno.mkdir(specDirectory, { recursive: true });
    await Deno.writeFile(artifactUrl, wasm);
    await Deno.writeFile(specUrl, spec);
    await Deno.writeFile(hashManifestUrl, hashManifest);
  }
} finally {
  await Deno.remove(buildDirectory, { recursive: true });
}
