const STELLAR_CLI_VERSION = "26.1.0";
const SOROBAN_SDK_VERSION = "28.0.0-rc.1";
const PACKAGE = "executable-ref-manager-contract";
const MANIFEST = "_internal/contracts/executable-ref-manager/Cargo.toml";
const WASM = "executable_ref_manager_contract.wasm";
const SPEC = "executable-ref-manager.ts";
const SPEC_EXPORT = "EXECUTABLE_REF_MANAGER_SPEC";

const check = Deno.args.includes("--check");
const root = new URL("../", import.meta.url);
const artifactDirectory = new URL("_internal/tests/compiled-contracts/", root);
const specDirectory = new URL("_internal/tests/specs/", root);
const manifestUrl = new URL(
  "executable-ref-fixture.sha256.json",
  artifactDirectory,
);

async function command(executable: string, args: string[]): Promise<string> {
  const output = await new Deno.Command(executable, {
    args,
    cwd: root,
    stdout: "piped",
    stderr: "inherit",
  }).output();
  if (!output.success) {
    throw new Error(`${executable} ${args.join(" ")} failed`);
  }
  return new TextDecoder().decode(output.stdout).trim();
}

async function sha256(value: Uint8Array): Promise<string> {
  const digest = await crypto.subtle.digest("SHA-256", value);
  return Array.from(new Uint8Array(digest))
    .map((byte) => byte.toString(16).padStart(2, "0"))
    .join("");
}

function specSource(entries: string[]): string {
  return [
    "// deno-coverage-ignore-file",
    "// Generated by _tools/build-executable-ref-fixture.ts. Do not edit.",
    'import { Spec } from "stellar-sdk/contract";',
    "",
    `export const ${SPEC_EXPORT} = new Spec([`,
    ...entries.map((entry) => `  ${JSON.stringify(entry)},`),
    "]);",
    "",
  ].join("\n");
}

async function sameFile(url: URL, expected: Uint8Array): Promise<boolean> {
  try {
    const actual = await Deno.readFile(url);
    return actual.length === expected.length &&
      actual.every((byte, index) => byte === expected[index]);
  } catch (cause) {
    if (cause instanceof Deno.errors.NotFound) return false;
    throw cause;
  }
}

const stellarVersion = await command("stellar", ["--version"]);
if (!stellarVersion.includes(`stellar ${STELLAR_CLI_VERSION}`)) {
  throw new Error(
    `Expected Stellar CLI ${STELLAR_CLI_VERSION}, got ${stellarVersion}`,
  );
}
const cargoManifest = await Deno.readTextFile(new URL(MANIFEST, root));
if (!cargoManifest.includes(`soroban-sdk = "=${SOROBAN_SDK_VERSION}"`)) {
  throw new Error(`Expected soroban-sdk ${SOROBAN_SDK_VERSION}`);
}

const buildDirectory = await Deno.makeTempDir({
  prefix: "colibri-executable-ref-fixture-",
});
try {
  await command("stellar", [
    "contract",
    "build",
    "--locked",
    "--package",
    PACKAGE,
    "--out-dir",
    buildDirectory,
  ]);
  const builtUrl = new URL(
    WASM,
    `file://${buildDirectory.replace(/\/?$/, "/")}`,
  );
  const wasm = await Deno.readFile(builtUrl);
  const entries = JSON.parse(
    await command("stellar", [
      "contract",
      "inspect",
      "--wasm",
      builtUrl.pathname,
      "--output",
      "xdr-base64-array",
    ]),
  ) as string[];
  const spec = new TextEncoder().encode(specSource(entries));
  const manifest = new TextEncoder().encode(
    `${
      JSON.stringify(
        {
          stellarCli: STELLAR_CLI_VERSION,
          sorobanSdk: SOROBAN_SDK_VERSION,
          artifacts: { [WASM]: await sha256(wasm) },
        },
        null,
        2,
      )
    }\n`,
  );
  const artifactUrl = new URL(WASM, artifactDirectory);
  const specUrl = new URL(SPEC, specDirectory);

  if (check) {
    const stale: string[] = [];
    if (!(await sameFile(artifactUrl, wasm))) stale.push(WASM);
    if (!(await sameFile(specUrl, spec))) stale.push(SPEC);
    if (!(await sameFile(manifestUrl, manifest))) {
      stale.push("executable-ref-fixture.sha256.json");
    }
    if (stale.length > 0) {
      throw new Error(`Stale executable-ref fixtures: ${stale.join(", ")}`);
    }
  } else {
    await Deno.mkdir(artifactDirectory, { recursive: true });
    await Deno.mkdir(specDirectory, { recursive: true });
    await Deno.writeFile(artifactUrl, wasm);
    await Deno.writeFile(specUrl, spec);
    await Deno.writeFile(manifestUrl, manifest);
  }
} finally {
  await Deno.remove(buildDirectory, { recursive: true });
}
