import {
  contractEventBindings,
  extractContractErrorMapFromSpec,
  extractContractEventsFromSpec,
} from "@colibri/core";
import { Spec } from "stellar-sdk/contract";
import type { GenerateBindingsOptions, GeneratedBindings } from "@/types.ts";
import { BindingError, Code } from "@/error.ts";
import { doc, identifier, quote, TypeMap } from "@/type-map.ts";
import { packageScaffold } from "@/scaffold.ts";

/** @internal Used by the writer to distinguish generated files from application code. */
export const GENERATED_MARKER =
  "// Generated by @colibri/contract-bindings. Replaceable: keep custom code outside this file.";
/** Renders a complete client and optional package scaffold, without I/O or code execution. */
export function generateBindings(
  input: Spec,
  options: GenerateBindingsOptions = {},
): GeneratedBindings {
  try {
    const className = options.className ?? "ContractClient";
    const spec = new Spec(input.entries.map((entry) => entry.toXdr("base64")));
    const model = new TypeMap(spec);
    validateOptions(options, className, model);
    const methods = spec.funcs();
    if (
      new Set(methods.map((method) => method.name.toString())).size !==
        methods.length
    ) throw new BindingError(Code.INVALID_SPEC, "Duplicate function names");
    const methodsType = methods.map((method) => {
      if (method.outputs.length > 1) {
        throw new BindingError(
          Code.INVALID_SPEC,
          "The Stellar SDK does not support multiple function outputs",
        );
      }
      if (
        new Set(method.inputs.map((input) => input.name.toString())).size !==
          method.inputs.length
      ) {
        throw new BindingError(
          Code.INVALID_SPEC,
          `Duplicate inputs in ${method.name}`,
        );
      }
      const output = method.outputs[0]
        ? model.type(method.outputs[0], "Output", true)
        : "null";
      return `${
        doc(
          method.doc.toString(),
          "Choose read for simulation or invoke for transaction submission.",
        )
      }\n${quote(method.name.toString())}: { input: ${
        model.fields(method.inputs, "Input")
      }; output: ${output} };`;
    }).join("\n");
    extractContractEventsFromSpec(spec); // Validate declarations before emitting typed properties.
    const events = contractEventBindings(spec).map((binding, index) => {
      const event = spec.events()[index];
      const topics = event.params.filter((param) =>
        param.location.name === "scSpecEventParamLocationTopicList"
      );
      return `${
        doc(
          event.doc.toString(),
          `ABI event ${binding.name}, occurrence ${binding.occurrence}.`,
        )
      }\nreadonly ${quote(binding.key)}: ContractEventDefinition<${
        model.fields(event.params, "Output")
      }, ${model.fields(topics, "Input")}>;`;
    }).join("\n");
    const errors = extractContractErrorMapFromSpec(spec);
    const sdk = options.target === "npm"
      ? "@stellar/stellar-sdk/contract"
      : "stellar-sdk/contract";
    const source = renderClient({
      className,
      spec,
      sdk,
      methodsType,
      events,
      declarations: model.declarations(),
      errors,
      options,
    });
    const files = {
      [options.output === "package" ? "generated/bindings.ts" : "bindings.ts"]:
        source,
    };
    return {
      files,
      scaffold: packageScaffold(options, className),
      warnings: spec.events().length ? [] : [
        "No event declarations in this spec. The contract may still emit events.",
      ],
    };
  } catch (cause) {
    if (cause instanceof BindingError) throw cause;
    throw new BindingError(
      Code.INVALID_SPEC,
      "Could not generate bindings from this spec",
      cause,
    );
  }
}

function validateOptions(
  options: GenerateBindingsOptions,
  className: string,
  model: TypeMap,
): void {
  if (
    !identifier(className) ||
    [
      "Contract",
      "ColibriError",
      "Spec",
      "Result",
      "ContractEventRegistry",
      "ContractEventDefinition",
      "ContractId",
      "KnownContractErrorMap",
      "ContractConstructorArgs",
      "createContractErrorMatcherPlugin",
    ].includes(className)
  ) {
    throw new BindingError(
      Code.INVALID_OPTIONS,
      "Choose a valid class name that does not shadow a runtime import",
    );
  }
  if (
    options.target !== undefined && !["jsr", "npm"].includes(options.target)
  ) throw new BindingError(Code.INVALID_OPTIONS, "Unknown target preset");
  if (
    options.output !== undefined &&
    !["files", "package"].includes(options.output)
  ) throw new BindingError(Code.INVALID_OPTIONS, "Unknown output mode");
  if (
    [...model.aliases.values()].some((name) =>
      className === `${name}Input` || className === `${name}Output`
    )
  ) {
    throw new BindingError(
      Code.INVALID_OPTIONS,
      "Class name collides with an ABI type alias",
    );
  }
}

type RenderArgs = {
  className: string;
  spec: Spec;
  sdk: string;
  methodsType: string;
  events: string;
  declarations: string;
  errors: unknown;
  options: GenerateBindingsOptions;
};
function renderClient(
  { className, spec, sdk, methodsType, events, declarations, errors, options }:
    RenderArgs,
): string {
  // Prefix every generated symbol with the class name to avoid collisions with ABI user types.
  const p = `${className}ABI`;
  return `${GENERATED_MARKER}
/** Typed bindings. The ABI does not distinguish reads from writes. @module */
import { Contract, ColibriError, createContractErrorMatcherPlugin, type ContractConstructorArgs, type ContractId, type ContractEventDefinition, type ContractEventRegistry, type KnownContractErrorMap } from "@colibri/core";
import { Spec, type Result } from ${quote(sdk)};

${declarations}

/** Complete method map. Both execution modes use this same ABI. */
export type ${p}Methods = { ${methodsType} };
/** Method names mapped to their native inputs. */
export type ${p}Inputs = { [Method in keyof ${p}Methods]: ${p}Methods[Method]["input"] };
/** Method names mapped to the SDK's actual decoded outputs. */
export type ${p}Outputs = { [Method in keyof ${p}Methods]: ${p}Methods[Method]["output"] };
/** A method and its correlated arguments. Empty argument objects may be omitted. */
export type ${p}Call<Method extends keyof ${p}Methods> = { [Name in Method]: { method: Name } & (keyof ${p}Inputs[Name] extends never ? { methodArgs?: ${p}Inputs[Name] } : ${p}Inputs[Name] extends Record<string, never> ? { methodArgs?: ${p}Inputs[Name] } : { methodArgs: ${p}Inputs[Name] }) }[Method];
/** Transaction configuration and authorization accepted by Core. */
export type ${p}Invocation = Pick<Parameters<Contract["invoke"]>[0], "config" | "auth">;
/** Raw Core metadata plus the decoded value (absent when Core has no return value). */
export type ${p}InvocationResult<Value> = Awaited<ReturnType<Contract["invoke"]>> & { value: Value | undefined };
/** Declared event definitions; omitted indexed fields become filter wildcards. */
export type ${p}Events = ContractEventRegistry & { ${events} };
/** Embedded immutable ABI entries. Construct a fresh Spec for each client. */
export const ${p}SpecEntries: readonly string[] = Object.freeze(${
    JSON.stringify(spec.entries.map((entry) => entry.toXdr("base64")), null, 2)
  });
/** Creates an independent SDK spec. Loading another ABI invalidates these generated types. */
export function create${p}Spec(): Spec { return new Spec([...${p}SpecEntries]); }
/** Contract error messages. Clone/extend this object before constructing your client. */
export const ${p}Errors: KnownContractErrorMap = ${
    JSON.stringify(errors, null, 2)
  };
/** Source identity at generation time; a deployed contract can later be upgraded. */
export const ${p}Provenance: Readonly<Record<string, unknown>> = JSON.parse(${
    quote(JSON.stringify(options.provenance ?? { kind: "spec" }))
  });
/** Prepare errors and pipeline plugins at construction. false disables automatic error matching. */
export type ${p}ConstructorArgs = ContractConstructorArgs & { errors?: KnownContractErrorMap | false };

/** Colibri client with typed simulation and transaction submission for every ABI function. */
export class ${className} extends Contract {
  /** Installs the embedded spec and error matcher once, alongside caller-owned plugins. */
  constructor({ errors = ${p}Errors, ...args }: ${p}ConstructorArgs) {
    const plugin = errors === false || Object.keys(errors).length === 0 ? undefined : createContractErrorMatcherPlugin(
      args.contractConfig.contractId ? [{ strategy: "contract-id", contractId: args.contractConfig.contractId as ContractId, errors }] : [{ strategy: "issued-from", issuedFrom: "root-invocation", errors }],
    );
    const plugins = args.contractConfig.plugins;
    super({ ...args, contractConfig: { ...args.contractConfig, spec: create${p}Spec(), plugins: {
      invokePipe: [...(plugin ? [plugin] : []), ...(plugins?.invokePipe ?? [])],
      readPipe: [...(plugin ? [plugin] : []), ...(plugins?.readPipe ?? [])],
    } } });
  }
  /** Event definitions bound to the current contract id. No RPC request is made. */
  override get events(): ${p}Events { return super.events as ${p}Events; }
  /** Simulates any declared function. Simulation does not establish that a function is read-only. */
  override async read<Method extends keyof ${p}Methods>(args: ${p}Call<Method>): Promise<${p}Outputs[Method]> {
    return await super.read(args) as ${p}Outputs[Method];
  }
  /** Submits through Core's invoke pipeline and retains its raw returnValue and transaction metadata. */
  override async invoke<Method extends keyof ${p}Methods>(args: ${p}Call<Method> & ${p}Invocation): Promise<${p}InvocationResult<${p}Outputs[Method]>> {
    const result = await super.invoke(args);
    let value: ${p}Outputs[Method] | undefined;
    try {
      value = result.returnValue === undefined ? undefined : this.getSpec().funcResToNative(args.method, result.returnValue) as ${p}Outputs[Method];
    } catch (cause) {
      // The transaction already succeeded. Retain its result; do not retry submission on a decode failure.
      throw ColibriError.unexpected({ domain: "contract", source: "@colibri/contract-bindings/generated", code: ${
    quote(Code.RESULT_DECODE_FAILED)
  }, message: "Failed to decode contract result", details: "The transaction succeeded, but its return value does not match the embedded ABI. Inspect meta.data.result and regenerate the bindings if the ABI changed.", cause, meta: { data: { method: args.method, result } } });
    }
    return { ...result, value };
  }
}
`;
}
