// Generated by @colibri/contract-bindings. Replaceable: keep custom code outside this file.
/**
 * Demo method names, contract specification, and error messages.
 * @module
 */
import type { KnownContractErrorMap } from "@colibri/core";
import { Spec } from "stellar-sdk/contract";

/** ABI method names. Choose read or invoke at the call site. */
export const DemoMethods = {
  summary: "summary",
  get_count: "get_count",
  increment: "increment",
  echo_summary: "echo_summary",
} as const;

/** The contract specification embedded at generation time. */
export const DemoSpec: Spec = new Spec([
  "AAAABAAAAC1FcnJvcnMgcmV0dXJuZWQgYnkgdGhlIGRlbW9uc3RyYXRpb24gY291bnRlci4AAAAAAAAAAAAADENvdW50ZXJFcnJvcgAAAAIAAAAoVGhlIGluY3JlbWVudCBtdXN0IGJlIGdyZWF0ZXIgdGhhbiB6ZXJvLgAAABBJbnZhbGlkSW5jcmVtZW50AAAAAQAAAB5UaGUgY291bnRlciBjYW5ub3QgZXhjZWVkIDEwMC4AAAAAAA1MaW1pdEV4Y2VlZGVkAAAAAAAAAg==",
  "AAAAAAAAADNSZWFkIGEgc3RydWN0dXJlZCBzdW1tYXJ5IHdpdGggYSBuYW1lZCBzdGF0dXMgZW51bS4AAAAAB3N1bW1hcnkAAAAAAAAAAAEAAAfQAAAADkNvdW50ZXJTdW1tYXJ5AAA=",
  "AAAABQAAAEdFbWl0dGVkIGFmdGVyIHRoZSBjb3VudGVyIGNoYW5nZXM7IGFjdGlvbiBjYW4gYmUgdXNlZCBpbiBldmVudCBmaWx0ZXJzLgAAAAAAAAAADENvdW50Q2hhbmdlZAAAAAEAAAANY291bnRfY2hhbmdlZAAAAAAAAAMAAAAAAAAABmFjdGlvbgAAAAAAEQAAAAEAAAAAAAAACW9sZF9jb3VudAAAAAAAAAQAAAAAAAAAAAAAAAluZXdfY291bnQAAAAAAAAEAAAAAAAAAAI=",
  "AAAAAwAAACRTdGF0dXMgb2YgdGhlIGRlbW9uc3RyYXRpb24gY291bnRlci4AAAAAAAAADUNvdW50ZXJTdGF0dXMAAAAAAAACAAAAAAAAAAVFbXB0eQAAAAAAAAAAAAAAAAAACENvdW50aW5nAAAAAQ==",
  "AAAAAQAAAB1DdXJyZW50IGNvdW50IGFuZCBpdHMgc3RhdHVzLgAAAAAAAAAAAAAOQ291bnRlclN1bW1hcnkAAAAAAAIAAAAAAAAABWNvdW50AAAAAAAABAAAAAAAAAAGc3RhdHVzAAAAAAfQAAAADUNvdW50ZXJTdGF0dXMAAAA=",
  "AAAAAAAAACdSZWFkIHRoZSBjdXJyZW50IGNvdW50LCBpbml0aWFsbHkgemVyby4AAAAACWdldF9jb3VudAAAAAAAAAAAAAABAAAABA==",
  "AAAAAAAAAEBJbmNyZWFzZSB0aGUgY291bnQgYnkgYSBwb3NpdGl2ZSBhbW91bnQsIHVwIHRvIGEgbWF4aW11bSBvZiAxMDAuAAAACWluY3JlbWVudAAAAAAAAAEAAAAAAAAAAmJ5AAAAAAAEAAAAAQAAA+kAAAAEAAAH0AAAAAxDb3VudGVyRXJyb3I=",
  "AAAAAAAAAERSZXR1cm4gYSBzdW1tYXJ5IHVuY2hhbmdlZCB0byBleGVyY2lzZSBuYW1lZCBpbnB1dCBhbmQgb3V0cHV0IHR5cGVzLgAAAAxlY2hvX3N1bW1hcnkAAAABAAAAAAAAAAdzdW1tYXJ5AAAAB9AAAAAOQ291bnRlclN1bW1hcnkAAAAAAAEAAAfQAAAADkNvdW50ZXJTdW1tYXJ5AAA=",
]);

/** Clone and customize these messages before constructing the client. */
export const DemoErrors: KnownContractErrorMap = {
  "1": {
    "message": "InvalidIncrement",
    "details": "The increment must be greater than zero.",
  },
  "2": {
    "message": "LimitExceeded",
    "details": "The counter cannot exceed 100.",
  },
};
