// Generated by @colibri/contract-bindings. Replaceable: keep custom code outside this file.
/**
 * Typed Colibri client for Demo.
 * @module
 */
import {
  ColibriError,
  Contract,
  type ContractId,
  createContractErrorMatcherPlugin,
} from "@colibri/core";
import { Spec } from "@colibri/core";
import { DemoErrors, DemoSpec } from "./constants.ts";
import type {
  DemoCall,
  DemoConstructorArgs,
  DemoEvents,
  DemoInvocation,
  DemoInvocationResult,
  DemoMethodMap,
  DemoOutputs,
} from "./types.ts";

export * from "./constants.ts";
export * from "./types.ts";

/** Simulate or invoke any function declared in the embedded contract spec. */
export class Demo extends Contract {
  /** Install a fresh spec and the prepared error map alongside existing plugins. */
  constructor({ errors = DemoErrors, ...args }: DemoConstructorArgs) {
    const contractId = args.contractConfig.contractId as ContractId | undefined;
    const matcher = errors === false || Object.keys(errors).length === 0
      ? undefined
      : createContractErrorMatcherPlugin(
        contractId ? [{ strategy: "contract-id", contractId, errors }] : [{
          strategy: "issued-from",
          issuedFrom: "root-invocation",
          errors,
        }],
      );
    const plugins = args.contractConfig.plugins;

    super({
      ...args,
      contractConfig: {
        ...args.contractConfig,
        spec: new Spec(DemoSpec.entries.map((entry) => entry.toXdr("base64"))),
        plugins: {
          invokePipe: [
            ...(matcher ? [matcher] : []),
            ...(plugins?.invokePipe ?? []),
          ],
          readPipe: [
            ...(matcher ? [matcher] : []),
            ...(plugins?.readPipe ?? []),
          ],
        },
      },
    });
  }

  /** Access event definitions bound to the current contract ID. */
  override get events(): DemoEvents {
    return super.events as DemoEvents;
  }

  /** Simulate a function and decode its result without submitting a transaction. */
  override async read<Method extends keyof DemoMethodMap>(
    args: DemoCall<Method>,
  ): Promise<DemoOutputs[Method]> {
    return await super.read(args) as DemoOutputs[Method];
  }

  /** Submit through Colibri and retain both the decoded value and raw result. */
  override async invoke<Method extends keyof DemoMethodMap>(
    args: DemoCall<Method> & DemoInvocation,
  ): Promise<DemoInvocationResult<DemoOutputs[Method]>> {
    const result = await super.invoke(args);
    let value: DemoOutputs[Method] | undefined;

    try {
      value = result.returnValue === undefined
        ? undefined
        : this.getSpec().funcResToNative(
          args.method,
          result.returnValue,
        ) as DemoOutputs[Method];
    } catch (cause) {
      // The transaction succeeded. Preserve its result so callers can inspect it.
      throw ColibriError.unexpected({
        domain: "contract",
        source: "@colibri/contract-bindings/generated",
        code: "CBG_006",
        message: "Failed to decode contract result",
        details:
          "The transaction succeeded but its result does not match the embedded ABI. " +
          "Inspect meta.data.result and regenerate the bindings if the ABI changed.",
        cause,
        meta: { data: { method: args.method, result } },
      });
    }

    return { ...result, value };
  }
}
