// Generated by @colibri/contract-bindings. Replaceable: keep custom code outside this file.
/**
 * Typed Colibri client for Demo.
 * @module
 */
import {
  Contract,
  type ContractId,
  createContractErrorMatcherPlugin,
} from "@colibri/core";
import { Spec } from "@colibri/core";
import { ContractMethods, DemoErrors, DemoSpec } from "./constants.ts";
import type {
  DemoCall,
  DemoConstructorArgs,
  DemoEvents,
  DemoInvocation,
  DemoInvocationResult,
  DemoMethod,
  DemoMethodMap,
  DemoOutputs,
} from "./types.ts";

export * from "./constants.ts";
export * from "./types.ts";

/** Simulate or invoke any function declared in the embedded contract spec. */
export class Demo extends Contract {
  /** Read a structured summary with a named status enum. */
  readonly summary: DemoMethod<"summary"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.Summary, methodArgs }),
    invoke: (options) =>
      this.invoke({
        ...options,
        method: ContractMethods.Summary,
        methodArgs: {},
      }),
  };

  /** Read the current count, initially zero. */
  readonly get_count: DemoMethod<"get_count"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetCount, methodArgs }),
    invoke: (options) =>
      this.invoke({
        ...options,
        method: ContractMethods.GetCount,
        methodArgs: {},
      }),
  };

  /** Increase the count by a positive amount, up to a maximum of 100. */
  readonly increment: DemoMethod<"increment"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.Increment, methodArgs }),
    invoke: (methodArgs, options) =>
      this.invoke({
        ...options,
        method: ContractMethods.Increment,
        methodArgs,
      }),
  };

  /** Return a summary unchanged to exercise named input and output types. */
  readonly echo_summary: DemoMethod<"echo_summary"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.EchoSummary, methodArgs }),
    invoke: (methodArgs, options) =>
      this.invoke({
        ...options,
        method: ContractMethods.EchoSummary,
        methodArgs,
      }),
  };

  /** Install a fresh spec and the prepared error map alongside existing plugins. */
  constructor({ errors = DemoErrors, ...args }: DemoConstructorArgs) {
    const contractId = args.contractConfig.contractId as ContractId | undefined;
    const matcher = errors === false || Object.keys(errors).length === 0
      ? undefined
      : createContractErrorMatcherPlugin(
        contractId ? [{ strategy: "contract-id", contractId, errors }] : [{
          strategy: "issued-from",
          issuedFrom: "root-invocation",
          errors,
        }],
      );
    const plugins = args.contractConfig.plugins;

    super({
      ...args,
      contractConfig: {
        ...args.contractConfig,
        spec: new Spec(DemoSpec.entries.map((entry) => entry.toXdr("base64"))),
        plugins: {
          invokePipe: [
            ...(matcher ? [matcher] : []),
            ...(plugins?.invokePipe ?? []),
          ],
          readPipe: [
            ...(matcher ? [matcher] : []),
            ...(plugins?.readPipe ?? []),
          ],
        },
      },
    });
  }

  /** Access event definitions bound to the current contract ID. */
  override get events(): DemoEvents {
    return super.events as DemoEvents;
  }

  /** Simulate a function and decode its result without submitting a transaction. */
  override async read<Method extends keyof DemoMethodMap>(
    args: DemoCall<Method>,
  ): Promise<DemoOutputs[Method]> {
    return await super.read(args) as DemoOutputs[Method];
  }

  /** Submit through Colibri and retain both the decoded value and raw result. */
  override async invoke<Method extends keyof DemoMethodMap>(
    args: DemoCall<Method> & DemoInvocation,
  ): Promise<DemoInvocationResult<DemoOutputs[Method]>> {
    const result = await super.invoke(args);
    return this.decodeInvocationResult<DemoOutputs[Method]>(
      args.method,
      result,
    );
  }
}
