// Generated by @colibri/contract-bindings. Replaceable: keep custom code outside this file.
/**
 * Demo contract types, function arguments, results, and events.
 * @module
 */
import type {
  Contract,
  ContractConstructorArgs,
  ContractEventDefinition,
  ContractEventRegistry,
  KnownContractErrorMap,
} from "@colibri/core";
import type { Result as StellarResult } from "stellar-sdk/contract";
import { DemoMethods } from "./constants.ts";

/** Errors returned by the demonstration counter. */
export enum CounterError {
  /** The increment must be greater than zero. */
  InvalidIncrement = 1,
  /** The counter cannot exceed 100. */
  LimitExceeded = 2,
}

/** Status of the demonstration counter. */
export enum CounterStatus {
  Empty = 0,
  Counting = 1,
}

/** Current count and its status. */
export type CounterSummary = {
  count: number;
  status: CounterStatus;
};

/** Read a structured summary with a named status enum. */
export type SummaryInput = Record<string, never>;

/** Decoded return value of summary. */
export type SummaryOutput = CounterSummary;

/** Read the current count, initially zero. */
export type GetCountInput = Record<string, never>;

/** Decoded return value of get_count. */
export type GetCountOutput = number;

/** Increase the count by a positive amount, up to a maximum of 100. */
export type IncrementInput = {
  by: number;
};

/** Decoded return value of increment. */
export type IncrementOutput = StellarResult<number, { message: string }>;

/** Return a summary unchanged to exercise named input and output types. */
export type EchoSummaryInput = {
  summary: CounterSummary;
};

/** Decoded return value of echo_summary. */
export type EchoSummaryOutput = CounterSummary;

/** Every ABI method is available through both read and invoke. */
export type DemoMethodMap = {
  [DemoMethods.summary]: {
    input: SummaryInput;
    output: SummaryOutput;
  };
  [DemoMethods.get_count]: {
    input: GetCountInput;
    output: GetCountOutput;
  };
  [DemoMethods.increment]: {
    input: IncrementInput;
    output: IncrementOutput;
  };
  [DemoMethods.echo_summary]: {
    input: EchoSummaryInput;
    output: EchoSummaryOutput;
  };
};

/** Method names mapped to their native arguments. */
export type DemoInputs = {
  [Method in keyof DemoMethodMap]: DemoMethodMap[Method]["input"];
};

/** Method names mapped to their decoded return values. */
export type DemoOutputs = {
  [Method in keyof DemoMethodMap]: DemoMethodMap[Method]["output"];
};

/** A method and its matching arguments; argument-free calls may omit methodArgs. */
export type DemoCall<Method extends keyof DemoMethodMap> = {
  [Name in Method]:
    & { method: Name }
    & (
      DemoInputs[Name] extends Record<string, never>
        ? { methodArgs?: DemoInputs[Name] }
        : { methodArgs: DemoInputs[Name] }
    );
}[Method];

/** Transaction settings and authorization passed to Colibri. */
export type DemoInvocation = Pick<
  Parameters<Contract["invoke"]>[0],
  "config" | "auth"
>;

/** Core transaction metadata and the decoded contract result. */
export type DemoInvocationResult<Value> =
  & Awaited<ReturnType<Contract["invoke"]>>
  & { value: Value | undefined };

/** Configure the contract and prepare error messages before construction. */
export type DemoConstructorArgs = ContractConstructorArgs & {
  errors?: KnownContractErrorMap | false;
};

/**
 * Emitted after the counter changes; action can be used in event filters.
 */
export type CountChanged = {
  action: string;
  old_count: number;
  new_count: number;
};

/** Indexed fields accepted by the CountChanged event filters. */
export type CountChangedTopics = {
  action: string;
};

/** Event definitions bound to this client, with typed decoding and filters. */
export type DemoEvents = ContractEventRegistry & {
  readonly CountChanged: ContractEventDefinition<
    CountChanged,
    CountChangedTopics
  >;
};
