// Generated by @colibri/contract-bindings. Replaceable: keep custom code outside this file.
/**
 * Demo contract types, function arguments, results, and events.
 * @module
 */
import type {
  Contract,
  ContractConstructorArgs,
  ContractErrorMap,
  ContractEventDefinition,
  ContractEventRegistry,
} from "@colibri/core";
import type { Result as StellarResult } from "@colibri/core";
import type {
  SorobanSymbolInput,
  SorobanSymbolNative,
  SorobanU32Input,
  SorobanU32Native,
  SorobanValue,
} from "@colibri/core";
import { createSorobanFactory } from "@colibri/core";
import { DemoSpec } from "./constants.ts";

// -----------------------------------------------------------------------------
// Methods
// -----------------------------------------------------------------------------

/** Read a structured summary with a named status enum. */
export type SummaryInput = Record<string, never>;

/** Decoded return value of summary. */
export type SummaryOutput = CounterSummary;

/** Read the current count, initially zero. */
export type GetCountInput = Record<string, never>;

/** Decoded return value of get_count. */
export type GetCountOutput = SorobanU32Native;

/** Increase the count by a positive amount, up to a maximum of 100. */
export type IncrementInput = {
  by: SorobanU32Input;
};

/** Decoded return value of increment. */
export type IncrementOutput = StellarResult<
  SorobanU32Native,
  { message: string }
>;

/** Return a summary unchanged to exercise named input and output types. */
export type EchoSummaryInput = {
  summary: CounterSummaryInput;
};

/** Decoded return value of echo_summary. */
export type EchoSummaryOutput = CounterSummary;

/** Every ABI method is available through both read and invoke. */
export type DemoMethodMap = {
  summary: {
    input: SummaryInput;
    output: SummaryOutput;
  };
  get_count: {
    input: GetCountInput;
    output: GetCountOutput;
  };
  increment: {
    input: IncrementInput;
    output: IncrementOutput;
  };
  echo_summary: {
    input: EchoSummaryInput;
    output: EchoSummaryOutput;
  };
};

/** Method names mapped to their native arguments. */
export type DemoInputs = {
  [Method in keyof DemoMethodMap]: DemoMethodMap[Method]["input"];
};

/** Method names mapped to their decoded return values. */
export type DemoOutputs = {
  [Method in keyof DemoMethodMap]: DemoMethodMap[Method]["output"];
};

/** A method and its matching arguments; argument-free calls may omit methodArgs. */
export type DemoCall<Method extends keyof DemoMethodMap> = {
  [Name in Method]:
    & { method: Name }
    & (
      DemoInputs[Name] extends Record<string, never>
        ? { methodArgs?: DemoInputs[Name] }
        : { methodArgs: DemoInputs[Name] }
    );
}[Method];

/** Transaction settings and authorization passed to Colibri. */
export type DemoInvocation = Pick<
  Parameters<Contract["invoke"]>[0],
  "config" | "auth"
>;

/** Core transaction metadata and the decoded contract result. */
export type DemoInvocationResult<Value> =
  & Awaited<ReturnType<Contract["invoke"]>>
  & { value: Value | undefined };

// -----------------------------------------------------------------------------
// Contract types
// -----------------------------------------------------------------------------

/** Status of the demonstration counter. */
export enum CounterStatus {
  Empty = 0,
  Counting = 1,
}

/** Current count and its status. */
export type CounterSummary = {
  count: SorobanU32Native;
  status: CounterStatus;
};

/** Input accepted for CounterSummary; decoded values use CounterSummary. */
export type CounterSummaryInput =
  | {
    count: SorobanU32Input;
    status: CounterStatus | SorobanValue<CounterStatus>;
  }
  | SorobanValue<CounterSummary>;

/** Validate and encode the CounterStatus codes declared by this contract. */
export const CounterStatusType = createSorobanFactory<CounterStatus>(
  () => DemoSpec,
  "CounterStatus",
);

/** Validate, encode and decode CounterSummary using its contract declaration. */
export const CounterSummary = createSorobanFactory<
  CounterSummaryInput,
  CounterSummary
>(() => DemoSpec, "CounterSummary");

// -----------------------------------------------------------------------------
// Events
// -----------------------------------------------------------------------------

/**
 * Emitted after the counter changes; action can be used in event filters.
 */
export type CountChanged = {
  action: SorobanSymbolNative;
  old_count: SorobanU32Native;
  new_count: SorobanU32Native;
};

/** Indexed fields accepted by the CountChanged event filters. */
export type CountChangedTopics = {
  action: SorobanSymbolInput;
};

/** Event definitions bound to this client, with typed decoding and filters. */
export type DemoEvents = ContractEventRegistry & {
  readonly CountChanged: ContractEventDefinition<
    CountChanged,
    CountChangedTopics
  >;
};

// -----------------------------------------------------------------------------
// Client configuration
// -----------------------------------------------------------------------------

/** Configure the contract and prepare error messages before construction. */
export type DemoConstructorArgs = ContractConstructorArgs & {
  errors?: ContractErrorMap | false;
};
