/**
 * Focused contract APIs.
 * @module
 */
export * from "@/contract/index.ts";
export type * from "@/contract/types.ts";
export { Spec } from "@/contract/spec.ts";

// Shared public types are erased from JavaScript consumer bundles.
export type * from "@/common/types/transaction-config/resources.ts";
export type {
  AnyContractErrorMatcher,
  AuthEntrySigner,
  BaseFee,
  BaseLedgerEntry,
  BinaryData,
  BuildContractDataLedgerKeyArgs,
  ContractDataDurabilityName,
  ContractDataLedgerEntry,
  ContractErrorMap,
  ContractErrorMatcher,
  ContractExecutableLedgerObservation,
  ContractExecutableView,
  ContractId,
  ContractIdContractErrorMatcher,
  createInvokeContractPipeline,
  createReadFromContractPipeline,
  CustomNetworkConfig,
  DoubleWildcard,
  Ed25519PublicKey,
  EnvelopeSigner,
  Event,
  EventFilter,
  EventId,
  ExtraSignerKey,
  FutureNetConfig,
  HorizonConfig,
  InclusionFee,
  INetworkConfig,
  InvokeContractPipeline,
  IssuedFromContractErrorMatcher,
  KnownContractErrorDefinition,
  LedgerEntryKind,
  LedgerEntryValueXdr,
  LedgerEntryXdr,
  MainNetConfig,
  MaxFee,
  MuxedAddress,
  NetworkConfig,
  NetworkPassphrase,
  NetworkType,
  ParsedSimulationErrorIssuer,
  PreAuthTransactionSigner,
  PreAuthTx,
  ReadFromContractPipeline,
  RPCConfig,
  Segment,
  Sha256Hash,
  SignedPayload,
  Signer,
  SignerKey,
  SorobanCodec,
  SorobanScValInput,
  SorobanValue,
  TestNetConfig,
  TopicFilter,
  TransactionConfig,
  TransactionFee,
  TransactionSource,
  TransactionXDRBase64,
} from "@/types.ts";
