import { literal } from "@/generation/literal.ts";
import { extractContractErrorMapFromSpec } from "@colibri/core";
import type { Spec } from "@colibri/core";
import type { GenerateBindingsOptions } from "@/types.ts";
import { property, quote } from "@/generation/type-map.ts";

/** @internal Shared source marker used by the renderer and regeneration guard. */
export const GENERATED_MARKER =
  "// Generated by @colibri/contract-bindings. Replaceable: keep custom code outside this file.";
/** @internal Render method constants, the embedded spec and editable error metadata. */
export function renderConstants(
  spec: Spec,
  className: string,
  options: GenerateBindingsOptions,
): string {
  return `${GENERATED_MARKER}
/**
 * ${className} method names, contract specification, and error messages.
 * @module
 */
import type { KnownContractErrorMap } from "@colibri/core";
import { Spec } from "@colibri/core";

/** ABI method names. Choose read or invoke at the call site. */
export const ${className}Methods = {
${
    spec.funcs().map((method) =>
      `  ${property(method.name.toString())}: ${quote(method.name.toString())},`
    ).join("\n")
  }
} as const;

/** The contract specification embedded at generation time. */
export const ${className}Spec: Spec = new Spec([
${spec.entries.map((entry) => `  ${quote(entry.toXdr("base64"))},`).join("\n")}
]);

/** Clone and customize these messages before constructing the client. */
export const ${className}Errors: KnownContractErrorMap = ${
    literal(extractContractErrorMapFromSpec(spec))
  };
${
    options.provenance
      ? `
/** Source identity captured during generation; included by request. */
export const ${className}Provenance = ${literal(options.provenance)} as const;
`
      : ""
  }`;
}
