// deno-coverage-ignore-file
// Generated by _tools/build-executable-ref-fixture.ts. Do not edit.
import { Spec } from "stellar-sdk/contract";

export const EXECUTABLE_REF_MANAGER_SPEC = new Spec([
  "AAAAAAAAAAAAAAADZ2V0AAAAAAEAAAAAAAAAA3RhZwAAAAAQAAAAAQAAA+gAAAPuAAAAIA==",
  "AAAAAAAAAAAAAAADc2V0AAAAAAIAAAAAAAAAA3RhZwAAAAAQAAAAAAAAAAl3YXNtX2hhc2gAAAAAAAPuAAAAIAAAAAA=",
]);
