import type {
  ParsedSimulationContractErrorStackItem,
  ParsedSimulationErrorIssuer,
} from "@/common/helpers/contract-error-from-failed-simulation-response.ts";
import type { SimulateTransactionInput } from "@/processes/simulate-transaction/types.ts";
import type { ContractId } from "@/strkeys/types.ts";

/**
 * Human-facing information associated with a known contract error code.
 *
 * Contract bindings commonly generate maps shaped like
 * `{ 1: { message: "Unauthorized" } }`. Colibri uses this message when the
 * matcher plugin recognizes the corresponding contract error code.
 */
export type KnownContractErrorDefinition = {
  /** Message shown when this known contract error is recognized. */
  message: string;
};

/**
 * Error-code mapping generated by contract bindings or provided manually.
 *
 * Keys are numeric contract error codes and values describe the known error.
 * A plain map matches the first stack item with a known code regardless of
 * which contract emitted it.
 */
export type KnownContractErrorMap = Readonly<
  Record<number, KnownContractErrorDefinition>
>;

/**
 * Matching strategy used by a known contract-error matcher entry.
 *
 * `any` matches by code only, `contract-id` also requires a specific emitting
 * contract id, and `issued-from` limits matching to root or sub-invocation
 * errors. Matcher entries are evaluated in the order provided.
 */
export type ContractErrorMatcherStrategy =
  | "any"
  | "contract-id"
  | "issued-from";

/**
 * Matches any contract-error stack item by numeric code.
 *
 * This is the simplest strategy and is appropriate when all relevant contracts
 * use the same error-code mapping.
 */
export type AnyContractErrorMatcher = {
  /** Strategy discriminator. */
  strategy: "any";
  /** Error-code map used by this matcher. */
  errors: KnownContractErrorMap;
};

/**
 * Matches only stack items emitted by a specific contract id.
 *
 * Use this when different contracts can emit the same numeric error code with
 * different meanings.
 */
export type ContractIdContractErrorMatcher = {
  /** Strategy discriminator. */
  strategy: "contract-id";
  /** Contract id that must have emitted the error. */
  contractId: ContractId;
  /** Error-code map used by this matcher. */
  errors: KnownContractErrorMap;
};

/**
 * Matches only root-invocation or sub-invocation stack items.
 *
 * Use this when you want to distinguish errors emitted by the top-level
 * simulated contract call from errors emitted by contracts it called.
 */
export type IssuedFromContractErrorMatcher = {
  /** Strategy discriminator. */
  strategy: "issued-from";
  /** Invocation level that must have emitted the error. */
  issuedFrom: ParsedSimulationErrorIssuer;
  /** Error-code map used by this matcher. */
  errors: KnownContractErrorMap;
};

/**
 * One ordered matcher entry used by the plugin.
 *
 * The plugin scans matcher entries in order and throws the known-error wrapper
 * for the first configured strategy that recognizes a contract-error stack
 * item.
 */
export type ContractErrorMatcher =
  | AnyContractErrorMatcher
  | ContractIdContractErrorMatcher
  | IssuedFromContractErrorMatcher;

/**
 * Plugin configuration. A plain map is equivalent to one `any` matcher.
 *
 * Pass a plain map for the common case, or an ordered array of matcher entries
 * when you need contract-id or root/sub-invocation specific matching.
 *
 * @example Simple code-only mapping.
 * ```ts
 * const contractErrors = {
 *   1: { message: "Unauthorized" },
 *   2: { message: "AlreadyInitialized" },
 * };
 * ```
 *
 * @example Ordered strategy list.
 * ```ts
 * const contractErrors = [
 *   {
 *     strategy: "contract-id",
 *     contractId: tokenContractId,
 *     errors: tokenErrors,
 *   },
 *   {
 *     strategy: "issued-from",
 *     issuedFrom: "sub-invocation",
 *     errors: sharedErrors,
 *   },
 * ];
 * ```
 */
export type ContractErrorMatcherPluginConfig =
  | KnownContractErrorMap
  | readonly ContractErrorMatcher[];

/**
 * Contract-error stack item selected by the matcher.
 *
 * The selected match is exposed through
 * `KNOWN_CONTRACT_ERROR_SIMULATION_FAILED.meta.data.match`, while the original
 * `CONTRACT_ERROR_SIMULATION_FAILED` remains available as `meta.cause`.
 */
export type KnownContractErrorMatch = {
  /** Numeric contract error code. */
  code: number;
  /** Human-facing message configured for the code. */
  message: string;
  /** Contract that emitted the matched diagnostic error event. */
  contractId: ContractId;
  /** Whether the matched error was emitted by the root or a sub-invocation. */
  issuedFrom: ParsedSimulationErrorIssuer;
  /** Index of the matched diagnostic event. */
  eventIndex: number;
  /** Strategy that produced the match. */
  strategy: ContractErrorMatcherStrategy;
  /** Index of the matcher entry that produced the match. */
  matcherIndex: number;
};

/**
 * Runtime plugin returned by {@link createContractErrorMatcherPlugin}.
 *
 * Most users do not need to call these methods directly. Attach the plugin to a
 * pipeline with `pipeline.use(...)`, pass it intentionally through
 * `ContractConfig.plugins`, or use `Contract.loadContractErrorsFromWasm(...)`
 * when the mapping should be derived from a contract spec or WASM.
 */
export type ContractErrorMatcherPlugin = {
  /** Stable plugin id. */
  readonly id: string;
  /** Step id targeted by this plugin. */
  readonly target: "simulate-transaction";
  /**
   * Returns whether the plugin implements the given hook capability.
   *
   * @param capability - Plugin lifecycle capability name.
   * @returns Whether the plugin supports the capability.
   */
  supports(capability: string): boolean;
  /**
   * Returns whether this plugin should run for a given step id.
   *
   * @param stepId - Candidate step id.
   * @returns Whether the plugin targets the step.
   */
  targets(stepId: string): boolean;
  /**
   * Rewrites recognized simulate-transaction errors.
   *
   * @param error - Error emitted by the simulate-transaction step.
   * @param input - Original simulate-transaction step input.
   * @returns The original error or a known contract-error plugin failure.
   */
  error(
    error: Error,
    input: [SimulateTransactionInput],
  ): Error | Promise<Error>;
};

/** @internal */
export type ContractErrorMatcherCandidate =
  ParsedSimulationContractErrorStackItem;
