import { assertEquals, assertInstanceOf, assertThrows } from "@std/assert";
import { describe, it } from "@std/testing/bdd";
import { Keypair, xdr } from "stellar-sdk";
import { LocalSigner } from "@/signer/local/index.ts";
import { isMessageSigner, isSigner } from "@/common/type-guards/is-signer.ts";
import type { MessageSigner } from "@/signer/types.ts";
import * as E from "@/signer/local/error.ts";
import { toUint8Array } from "@/common/helpers/internal-bytes.ts";
const decodeBase64 = (value: string): Uint8Array =>
  xdr.decodeBytes(value, "base64");

describe("SEP-53 message signer capability", () => {
  it("matches the three independent published SEP-53 test vectors byte for byte", () => {
    // Public test-only seed and expected signatures from stellar-protocol SEP-0053,
    // version 1.0.0. These are not generated by the implementation under test.
    using signer = LocalSigner.fromSecret(
      "SAKICEVQLYWGSOJS4WW7HZJWAHZVEEBS527LHK5V4MLJALYKICQCJXMW",
    );
    const vectors: [string | Uint8Array, string][] = [
      [
        "Hello, World!",
        "fO5dbYhXUhBMhe6kId/cuVq/AfEnHRHEvsP8vXh03M1uLpi5e46yO2Q8rEBzu3feXQewcQE5GArp88u6ePK6BA==",
      ],
      [
        "こんにちは、世界！",
        "CDU265Xs8y3OWbB/56H9jPgUss5G9A0qFuTqH2zs2YDgTm+++dIfmAEceFqB7bhfN3am59lCtDXrCtwH2k1GBA==",
      ],
      [
        decodeBase64("2zZDP1sa1BVBfLP7TeeMk3sUbaxAkUhBhDiNdrksaFo="),
        "VA1+7hefNwv2NKScH6n+Sljj15kLAge+M2wE7fzFOf+L0MMbssA1mwfJZRyyrhBORQRle10X1Dxpx+UOI4EbDQ==",
      ],
    ];
    for (const [message, signature] of vectors) {
      assertEquals(signer.signMessage(message), decodeBase64(signature));
      assertEquals(
        signer.verifyMessage(message, decodeBase64(signature)),
        true,
      );
      assertEquals(
        signer.verifyMessage("wrong message", decodeBase64(signature)),
        false,
      );
    }
    signer.destroy();
    assertEquals(
      signer.verifyMessage(vectors[0][0], decodeBase64(vectors[0][1])),
      true,
    );
    const error = assertThrows(
      () =>
        signer.verifyMessage(
          42 as unknown as string,
          decodeBase64(vectors[0][1]),
        ),
      E.MESSAGE_VERIFICATION_FAILED,
    );
    assertInstanceOf(error.meta.cause, Error);
    assertEquals(E.ERROR_SIG_LOC[error.code], E.MESSAGE_VERIFICATION_FAILED);
  });
  it("signs text and equivalent UTF-8 bytes using the native format", () => {
    using signer = LocalSigner.generateRandom();
    const message = "Approve revision 42: olá 🐦";
    const bytes = new TextEncoder().encode(message);
    const verifier = Keypair.fromPublicKey(signer.publicKey());
    const signature = signer.signMessage(message);
    assertInstanceOf(signature, Uint8Array);
    assertEquals(signature.length, 64);
    assertEquals(signature, signer.signMessage(bytes));
    assertEquals(verifier.verifyMessage(message, signature), true);
    assertEquals(verifier.verifyMessage(bytes, signature), true);
    assertEquals(verifier.verifyMessage("different intent", signature), false);
    assertEquals(verifier.verify(bytes, signature), false);
    assertEquals(
      verifier.verifyMessage(message, toUint8Array(signer.sign(bytes))),
      false,
    );
  });

  it("supports empty messages and arbitrary binary bytes without conversion", () => {
    using signer = LocalSigner.generateRandom(true);
    const native = Keypair.fromPublicKey(signer.publicKey());
    for (
      const message of ["", new Uint8Array(), new Uint8Array([0, 255, 128])]
    ) {
      assertEquals(
        native.verifyMessage(message, signer.signMessage(message)),
        true,
      );
    }
  });

  it("uses unique typed errors for destroyed signers and invalid message input", () => {
    using signer = LocalSigner.generateRandom();
    const error = assertThrows(
      () => signer.signMessage(42 as unknown as Uint8Array),
      E.MESSAGE_SIGNING_FAILED,
    );
    assertInstanceOf(error.meta.cause, TypeError);
    assertEquals(error.code, E.Code.MESSAGE_SIGNING_FAILED);
    signer.destroy();
    const destroyed = assertThrows(
      () => signer.signMessage("message"),
      E.MESSAGE_SIGNER_DESTROYED,
    );
    assertEquals(destroyed.code, E.Code.MESSAGE_SIGNER_DESTROYED);
    assertEquals(E.ERROR_SIG_LOC[error.code], E.MESSAGE_SIGNING_FAILED);
    assertEquals(E.ERROR_SIG_LOC[destroyed.code], E.MESSAGE_SIGNER_DESTROYED);
  });

  it("recognizes sync and asynchronous capabilities without granting transaction eligibility", async () => {
    using local = LocalSigner.generateRandom();
    const messageOnly: MessageSigner = {
      publicKey: () => local.publicKey(),
      signMessage: (message) => Promise.resolve(local.signMessage(message)),
    };
    assertEquals(isMessageSigner(local), true);
    assertEquals(isMessageSigner(messageOnly), true);
    assertEquals(isSigner(messageOnly), false);
    assertEquals(
      Keypair.fromPublicKey(messageOnly.publicKey()).verifyMessage(
        "message",
        await messageOnly.signMessage("message"),
      ),
      true,
    );
  });

  it("rejects absent, non-callable and incomplete capability members", () => {
    for (
      const value of [
        null,
        undefined,
        42,
        {},
        { publicKey: "G...", signMessage: () => new Uint8Array() },
        { publicKey: () => "G..." },
        { publicKey: () => "G...", signMessage: "not callable" },
      ]
    ) assertEquals(isMessageSigner(value), false);
  });
});
